# Generated via
#  `rails generate hyrax:work Article`
module Hyrax
  class ArticlePresenter < Hyrax::WorkShowPresenter
    delegate :editor,
    :has_journal,
    :has_number,
    :has_volume,
    :is_referenced_by,
    :web_of_science_uid,
    :abstract,
    :academic_affiliation,
    :alt_title,
    :bibliographic_citation,
    :conference_location,
    :conference_name,
    :contributor,
    :creator,
    :date_available,
    :date_created,
    :date_issued,
    :doi,
    :file_extent,
    :file_format,
    :identifier,
    :in_series,
    :isbn,
    :issn,
    :keyword,
    :language,
    :other_affiliation,
    :publisher,
    :replaces,
    :resource_type,
    :rights_statement, to: :solr_document
  end
end
# :additional_information,
# :embargo_reason,
# :peerreviewed,