terms:
  - id: "University of Colorado Boulder"
    term: "University of Colorado Boulder"
    active: true
    admin_only: false
  - id: "Other"
    term: "Other"
    active: true
    admin_only: false
