terms:
- id: A&S ASSETT
  term: A&S ASSETT
- id: Academic Advising Center
  term: Academic Advising Center
- id: Academic Affairs
  term: Academic Affairs
- id: Admissions
  term: Admissions
- id: Advertising, Public Relations and Media Design
  term: Advertising, Public Relations and Media Design
- id: Aerospace Engineering Sciences
  term: Aerospace Engineering Sciences
- id: Alumni Association
  term: Alumni Association
- id: Anthropology
  term: Anthropology
- id: Applied Mathematics
  term: Applied Mathematics
- id: Art & Art History-Gallery
  term: Art & Art History-Gallery
- id: Art and Art History
  term: Art and Art History
- id: Asian Languages and Civilizations
  term: Asian Languages and Civilizations
- id: Astrophysical and Planetary Sciences (APS)
  term: Astrophysical and Planetary Sciences (APS)
- id: Atmospheric and Oceanic Sciences (ATOC)
  term: Atmospheric and Oceanic Sciences (ATOC)
- id: Biochemistry
  term: Biochemistry
- id: Boulder Faculty Assembly
  term: Boulder Faculty Assembly
- id: Career Svcs-Central Office
  term: Career Svcs-Central Office
- id: Center for Environmental Journalism
  term: Center for Environmental Journalism
- id: Center for Media, Religion and Culture
  term: Center for Media, Religion and Culture
- id: Center for Medieval and Early Modern Studies
  term: Center for Medieval and Early Modern Studies
- id: Center for STEM Learning
  term: Center for STEM Learning
- id: Center for Western Civilization
  term: Center for Western Civilization
- id: Chemical and Biological Engineering
  term: Chemical and Biological Engineering
- id: Chemistry
  term: Chemistry
- id: Cinema Studies & Moving Image Arts
  term: Cinema Studies & Moving Image Arts
- id: Civil, Environmental and Architectural Engineering
  term: Civil, Environmental and Architectural Engineering
- id: Classics
  term: Classics
- id: Communication
  term: Communication
- id: Computer Science
  term: Computer Science
- id: Conference on World Affairs
  term: Conference on World Affairs
- id: Conservative Thought
  term: Conservative Thought
- id: Continuing Education & Professional Studies
  term: Continuing Education & Professional Studies
- id: Critical Media Practices
  term: Critical Media Practices
- id: CS Post Bacc Program
  term: CS Post Bacc Program
- id: Ctr for the Study of Origins
  term: Ctr for the Study of Origins
- id: CU at DC Internship
  term: CU at DC Internship
- id: Ecology and Evolutionary Biology
  term: Ecology and Evolutionary Biology
- id: Economics
  term: Economics
- id: Electrical, Computer and Energy Engineering (ECEE)
  term: Electrical, Computer and Energy Engineering (ECEE)
- id: Employee Services
  term: Employee Services
- id: Engineering-Bold Center
  term: Engineering-Bold Center
- id: English
  term: English
- id: Environmental Center
  term: Environmental Center
- id: Environmental Design
  term: Environmental Design
- id: Environmental Studies Program
  term: Environmental Studies Program
- id: Ethnic Studies
  term: Ethnic Studies
- id: Fac Man-Administration
  term: Fac Man-Administration
- id: Fac Man-Capital Construction
  term: Fac Man-Capital Construction
- id: Faculty Affairs
  term: Faculty Affairs
- id: Faculty Council, A&S
  term: Faculty Council, A&S
- id: Faculty Teaching Excellence Program (FTEP)
  term: Faculty Teaching Excellence Program (FTEP)
- id: Financial Aid
  term: Financial Aid
- id: French & Italian
  term: French & Italian
- id: General Engineering
  term: General Engineering
- id: Geography
  term: Geography
- id: Geological Sciences
  term: Geological Sciences
- id: Germanic and Slavic Languages and Literatures
  term: Germanic and Slavic Languages and Literatures
- id: Global Engineering RAP
  term: Global Engineering RAP
- id: Graduate Teacher Program
  term: Graduate Teacher Program
- id: Health Professions RAP
  term: Health Professions RAP
- id: Herbst Humanities Program
  term: Herbst Humanities Program
- id: History
  term: History
- id: Honors Program
  term: Honors Program
- id: Housing & Dining Services
  term: Housing & Dining Services
- id: Humanities
  term: Humanities
- id: Information Science
  term: Information Science
- id: Integrated Teaching & Learning (ITL) Program
  term: Integrated Teaching & Learning (ITL) Program
- id: Integrative Physiology
  term: Integrative Physiology
- id: Intermedia Art, Writing and Performance
  term: Intermedia Art, Writing and Performance
- id: International Education
  term: International Education
- id: International English Center (IEC)
  term: International English Center (IEC)
- id: IRISS Grand Challenge
  term: IRISS Grand Challenge
- id: Journalism
  term: Journalism
- id: Linguistics
  term: Linguistics
- id: Masters of the Environment
  term: Masters of the Environment
- id: Materials Engineering
  term: Materials Engineering
- id: Mathematics
  term: Mathematics
- id: Mechanical Engineering
  term: Mechanical Engineering
- id: Media Studies
  term: Media Studies
- id: MFA in Experience Design
  term: MFA in Experience Design
- id: Molecular, Cellular & Developmental Biology (MCDB)
  term: Molecular, Cellular & Developmental Biology (MCDB)
- id: National Snow &Ice Data Center (NSIDC)
  term: National Snow &Ice Data Center (NSIDC)
- id: National Solar Observatory
  term: National Solar Observatory
- id: Native American and Indigenous Studies
  term: Native American and Indigenous Studies
- id: NCWIT
  term: NCWIT
- id: New Student and Family Programs
  term: New Student and Family Programs
- id: Office of Business & Finance
  term: Office of Business & Finance
- id: Office of Data Analytics
  term: Office of Data Analytics
- id: Office of Diversity, Equity, and Community Engagement
  term: Office of Diversity, Equity, and Community Engagement
- id: Office of Technology Transfer
  term: Office of Technology Transfer
- id: Office of the Chancellor
  term: Office of the Chancellor
- id: OIT-Administration
  term: OIT-Administration
- id: Ombuds Office
  term: Ombuds Office
- id: Philosophy
  term: Philosophy
- id: Physics
  term: Physics
- id: Political Science
  term: Political Science
- id: Pre-Collegiate Programs
  term: Pre-Collegiate Programs
- id: President's Leadership Class
  term: President's Leadership Class
- id: Program for Writing and Rhetoric
  term: Program for Writing and Rhetoric
- id: Psychology and Neuroscience
  term: Psychology and Neuroscience
- id: Religious Studies
  term: Religious Studies
- id: Research & Engineering  Ctr for Unmanned Vehicles (RECUV)
  term: Research & Engineering  Ctr for Unmanned Vehicles (RECUV)
- id: Research & Innovation Office
  term: Research & Innovation Office
- id: Sociology
  term: Sociology
- id: Spanish and Portuguese
  term: Spanish and Portuguese
- id: Speech, Language, and Hearing Sciences (SLHS)
  term: Speech, Language, and Hearing Sciences (SLHS)
- id: STRATEGIC INIT, OFC OF
  term: STRATEGIC INIT, OFC OF
- id: Student Academic Services Center
  term: Student Academic Services Center
- id: Sustainability Innovation Lab
  term: Sustainability Innovation Lab
- id: Technology, Cybersecurity and Policy Program
  term: Technology, Cybersecurity and Policy Program
- id: Theatre and Dance
  term: Theatre and Dance
- id: UMC-Administration
  term: UMC-Administration
- id: Undergraduate Education
  term: Undergraduate Education
- id: Undergraduate Enrichment Programs
  term: Undergraduate Enrichment Programs
- id: University of Colorado Foundation
  term: University of Colorado Foundation
- id: University of Colorado President
  term: University of Colorado President
- id: VC Student Affairs
  term: VC Student Affairs
- id: Veterans Affairs
  term: Veterans Affairs
- id: Wellness Administration
  term: Wellness Administration
- id: Women and Gender Studies
  term: Women and Gender Studies
