#This file is in the order of `ModelName: "Admin Set Name"`
#If changes are being made to this file, please follow this order

nv935286k: "Article"
k643b116n: "GraduateThesisOrDissertation"
m326m172d: "UndergraduateHonorsThesis"
j6731378s: "Dataset"
0p0966899: "Presentation"
c534fn941: "ConferenceProceeding"
admin_set/default: "Default"
dn39x152w: "Book"
pr76f341v: "BookChapter"
j098zb08p: "Report"
qb98mf449: "GraduateThesisOrDissertation"
