#This file is in the order of `ModelName: "Admin Set Name"`
#If changes are being made to this file, please follow this order

Article: "Article"
GraduateThesisOrDissertation: "Graduate Thesis Or Dissertation"
UndergraduateHonorsThesis: "Undergraduate Honors Thesis"
Dataset: "Dataset"
Presentation: "Presentation"
ConferenceProceedings: "Conference Proceedings"
Default: "Default"
Book: "Book"
BookChapter: "Book Chapter"
Reports: "Reports"



