#This file is in the order of `ModelName: "Admin Set Name"`
#If changes are being made to this file, please follow this order

nv935286k: "Article"
k643b116n: "Graduate Thesis Or Dissertation"
m326m172d: "Undergraduate Honors Thesis"
j6731378s: "Dataset"
0p0966899: "Presentation"
c534fn941: "Conference Proceedings"
Default: "Default"
dn39x152w: "Book"
pr76f341v: "Book Chapter"
j098zb08p: "Reports"
