#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#
analytics:
  app_name: cu-scholar
  app_version: v2.6.0
  privkey_path: /data/cu-scholar-98ddf6f79202.p12
  privkey_secret: notasecret
  client_email: cu-scholar-account@cu-scholar-264616.iam.gserviceaccount.com
