# This is a sample config file that points to a solr server for each environment
development:
  adapter: solr
  url: <%= ENV.fetch('SCHOLARS_SOLR_URL', 'http://localhost:8983') %>/solr/hydra-development
test: &test
  adapter: solr
  url: <%= ENV.fetch('SCHOLARS_SOLR_URL', 'http://localhost:8985') %>/solr/hydra-test
production:
  adapter: solr
  url: <%= ENV.fetch('SCHOLARS_SOLR_URL', 'http://solr-svc:8983/solr/hydra-production') %>
staging:
  adapter: solr
  url: <%= ENV.fetch('SCHOLARS_SOLR_URL', 'http://solr-svc:8983/solr/hydra-staging') %> 

