# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  ##
  # @return [Valkyrie::ID]
  def representative_id=(_input)
    # saving a file set using valkyrie would err because this method didn't exist.
    Rails.logger.warn('This is not a valid method for file sets')
    id
  end

  private

  def set_defaults
  end

end
